version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:latest  # 기본 Flutter 이미지 사용
    working_directory: /workspace

jobs:
  build:
    executor: flutter-executor
    steps:
      - checkout  # 코드 체크아웃
      - run:
          name: Install Flutter SDK 3.29.0
          command: |
            flutter channel stable  # stable 채널로 변경
            flutter upgrade  # Flutter SDK를 최신 버전으로 업데이트
            flutter version 3.29.0  # 원하는 Flutter SDK 버전으로 설정
      - run:
          name: Install dependencies
          command: |
            flutter pub get  # Flutter 의존성 설치
      - run:
          name: Run tests
          command: |
            flutter test  # Flutter 테스트 실행
      - run:
          name: Build APK
          command: |
            flutter build apk --release  # APK 빌드
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk  # APK 파일을 Artifacts로 저장

workflows:
  version: 2
  build:
    jobs:
      - build  # 빌드 작업 실행