version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:latest  # 최신 Flutter 이미지 사용
    working_directory: ~/repo

jobs:
  build:
    executor: flutter-executor
    steps:
      - checkout  # Git 저장소에서 소스를 체크아웃
      - run:
          name: Install Flutter
          command: flutter upgrade  # Flutter SDK 최신 버전으로 업데이트
      - run:
          name: Flutter pub get
          command: flutter pub get  # 'flutter pub get' 명령어 실행

workflows:
  version: 2
  build:
    jobs:
      - build