version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:latest  # Flutter를 위한 Docker 이미지
    working_directory: /workspace  # 작업 디렉토리 설정

jobs:
  build:
    executor: flutter-executor
    steps:
      - checkout  # GitHub 저장소에서 코드 체크아웃

      # Flutter SDK 버전 3.7.0 강제 설정
      - run:
          name: Install Flutter SDK 3.7.0
          command: |
            git clone https://github.com/flutter/flutter.git /flutter
            cd /flutter
            git checkout 3.7.0  # 원하는 버전 체크아웃
            export PATH="$PATH:/flutter/bin"
            flutter doctor  # SDK 상태 확인

      # Flutter 의존성 설치
      - run:
          name: Install dependencies
          command: flutter pub get

      # Flutter APK 빌드
      - run:
          name: Build APK
          command: flutter build apk --release

      # APK 파일을 /tmp에 저장 (다른 경로로 변경 가능)
      - persist_to_workspace:
          root: /workspace
          paths:
            - build/app/outputs/flutter-apk/app-release.apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build